/* ──────────────────────────────────────────────
   Providers.tsx — Search CT mental health providers by ZIP code.
   Data is loaded from /ct_mental_health_providers.csv (PapaParse).
   ZIP center-point coordinates come from /ct_zip_coords.json so users
   can search within a mile radius. Filters: specialty category + city.
────────────────────────────────────────────── */

import { useState, useEffect, useMemo } from 'react'
import Papa from 'papaparse'
import Dropdown from '../components/Dropdown'

interface Provider {
  NPI: string
  'First Name': string
  'Last Name': string
  Credential: string
  Gender: string
  Specialty: string
  Address: string
  City: string
  State: string
  ZIP: string
  Phone: string
  'Insurance Accepted': string
  'Accepting New Patients': string
}

/* A provider plus how far their ZIP is from the searched ZIP */
type ProviderResult = Provider & { distanceMiles: number }

/* ZIP → [latitude, longitude] map generated by scripts/Pull_ct_zip_coords.py */
type ZipCoords = Record<string, [number, number]>

/* Straight-line ("as the crow flies") distance between two points, in miles */
function haversineMiles(a: [number, number], b: [number, number]): number {
  const EARTH_RADIUS_MI = 3958.8
  const toRad = (deg: number) => (deg * Math.PI) / 180
  const dLat = toRad(b[0] - a[0])
  const dLng = toRad(b[1] - a[1])
  const h =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(a[0])) * Math.cos(toRad(b[0])) * Math.sin(dLng / 2) ** 2
  return 2 * EARTH_RADIUS_MI * Math.asin(Math.sqrt(h))
}

/* Turn the CSV's "M"/"F" codes into a readable label */
function genderLabel(code: string): string {
  if (code === 'M') return 'Male'
  if (code === 'F') return 'Female'
  return ''
}

/* Map raw specialty strings to a simpler category label */
function toCategory(specialty: string): string {
  if (specialty.includes('Psychiatry')) return 'Psychiatry'
  if (specialty.includes('Psychologist')) return 'Psychology'
  if (specialty.includes('Counselor')) return 'Counseling'
  if (specialty.includes('Social Worker')) return 'Social Work'
  if (specialty.includes('Marriage & Family')) return 'Marriage & Family Therapy'
  if (specialty.includes('Nurse Practitioner') || specialty.includes('Clinical Nurse Specialist')) return 'Nurse Practitioner / CNS'
  return 'Other'
}

/* Radius choices shown in the "Distance" dropdown (0 = exact ZIP only) */
const RADIUS_OPTIONS = [
  { value: 0, label: 'Exact ZIP only' },
  { value: 5, label: 'Within 5 miles' },
  { value: 10, label: 'Within 10 miles' },
  { value: 25, label: 'Within 25 miles' },
  { value: 50, label: 'Within 50 miles' },
]

function Providers() {
  const [allProviders, setAllProviders] = useState<Provider[]>([])
  const [zipCoords, setZipCoords] = useState<ZipCoords>({})
  /* NPIs of CT clinicians enrolled in Medicare (from Pull_ct_medicare.py) */
  const [medicareNpis, setMedicareNpis] = useState<Record<string, string>>({})
  const [zip, setZip] = useState('')
  const [radius, setRadius] = useState(10)
  const [zipResults, setZipResults] = useState<ProviderResult[]>([])
  const [searched, setSearched] = useState(false)
  const [searchNote, setSearchNote] = useState('')
  const [loading, setLoading] = useState(true)

  /* Active filter values */
  const [filterCategory, setFilterCategory] = useState('All')
  const [filterCity, setFilterCity] = useState('All')

  /* Load the provider CSV and the ZIP coordinates once on mount */
  useEffect(() => {
    Papa.parse('/ct_mental_health_providers.csv', {
      download: true,
      header: true,
      skipEmptyLines: true,
      complete: (parsed) => {
        setAllProviders(parsed.data as Provider[])
        setLoading(false)
      },
    })

    fetch('/ct_zip_coords.json')
      .then((res) => res.json())
      .then((coords: ZipCoords) => setZipCoords(coords))

    fetch('/ct_medicare_npis.json')
      .then((res) => res.json())
      .then((npis: Record<string, string>) => setMedicareNpis(npis))
  }, [])

  function handleSearch() {
    const trimmed = zip.trim()
    if (!trimmed) return

    const origin = zipCoords[trimmed]
    let results: ProviderResult[]
    let note = ''

    if (radius > 0 && origin) {
      /* Radius search — keep providers whose ZIP center is within X miles,
         sorted nearest first */
      results = allProviders
        .map((p) => {
          const dest = zipCoords[p.ZIP]
          const distanceMiles = dest ? haversineMiles(origin, dest) : Infinity
          return { ...p, distanceMiles }
        })
        .filter((p) => p.distanceMiles <= radius)
        .sort((a, b) => a.distanceMiles - b.distanceMiles)
    } else {
      /* Exact-ZIP search — also the fallback when we have no coordinates
         for the ZIP the user typed */
      if (radius > 0 && !origin) {
        note = `We don't have map coordinates for ${trimmed}, so results show that exact ZIP only.`
      }
      results = allProviders
        .filter((p) => p.ZIP === trimmed)
        .map((p) => ({ ...p, distanceMiles: 0 }))
    }

    setZipResults(results)
    setSearchNote(note)
    setFilterCategory('All')
    setFilterCity('All')
    setSearched(true)
  }

  /* Unique filter options derived from the ZIP results */
  const categoryOptions = useMemo(() => {
    const cats = new Set(zipResults.map((p) => toCategory(p.Specialty)))
    return ['All', ...Array.from(cats).sort()]
  }, [zipResults])

  const cityOptions = useMemo(() => {
    const cities = new Set(zipResults.map((p) => p.City).filter(Boolean))
    return ['All', ...Array.from(cities).sort()]
  }, [zipResults])

  /* Apply filters on top of the ZIP results */
  const visibleResults = useMemo(() => {
    return zipResults.filter((p) => {
      if (filterCategory !== 'All' && toCategory(p.Specialty) !== filterCategory) return false
      if (filterCity !== 'All' && p.City !== filterCity) return false
      return true
    })
  }, [zipResults, filterCategory, filterCity])

  return (
    <section className="providers-page">
      <div className="providers-hero">
        <p className="coming-soon-label">Providers</p>
        <h1 className="providers-heading">Find a Provider Near You</h1>
        <p className="providers-sub">
          Enter a Connecticut ZIP code and how far you're willing to travel.
        </p>

        {/* ZIP code + travel distance search form */}
        <form className="zip-form" onSubmit={(e) => { e.preventDefault(); handleSearch() }}>
          <input
            type="text"
            className="zip-input"
            value={zip}
            onChange={(e) => setZip(e.target.value.replace(/\D/g, '').slice(0, 5))}
            placeholder="e.g. 06511"
            maxLength={5}
            inputMode="numeric"
            aria-label="ZIP code"
            disabled={loading}
          />
          <Dropdown
            options={RADIUS_OPTIONS.map((r) => ({ value: String(r.value), label: r.label }))}
            value={String(radius)}
            onChange={(v) => setRadius(Number(v))}
            ariaLabel="Travel distance"
            disabled={loading}
          />
          <button
            type="submit"
            className="zip-btn"
            disabled={loading || zip.trim().length !== 5}
          >
            {loading ? 'Loading…' : 'Search'}
          </button>
        </form>
      </div>

      {/* Filters + Results */}
      {searched && (
        <div className="providers-results">
          {/* Explains when a radius search fell back to exact-ZIP */}
          {searchNote && <p className="providers-note">{searchNote}</p>}

          {zipResults.length === 0 ? (
            <p className="providers-empty">
              No providers found{radius > 0 ? ` within ${radius} miles of` : ' for ZIP code'}{' '}
              <strong>{zip}</strong>. Try a wider distance or another ZIP.
            </p>
          ) : (
            <>
              {/* Filter bar */}
              <div className="filter-bar">
                <div className="filter-group">
                  <span className="filter-label">Specialty</span>
                  <Dropdown
                    options={categoryOptions.map((c) => ({ value: c, label: c }))}
                    value={filterCategory}
                    onChange={setFilterCategory}
                    ariaLabel="Filter by specialty"
                  />
                </div>

                <div className="filter-group">
                  <span className="filter-label">City</span>
                  <Dropdown
                    options={cityOptions.map((c) => ({ value: c, label: c }))}
                    value={filterCity}
                    onChange={setFilterCity}
                    ariaLabel="Filter by city"
                  />
                </div>

                {/* Reset filters */}
                {(filterCategory !== 'All' || filterCity !== 'All') && (
                  <button
                    className="filter-reset"
                    onClick={() => { setFilterCategory('All'); setFilterCity('All') }}
                  >
                    Clear filters
                  </button>
                )}
              </div>

              <p className="providers-count">
                Showing {visibleResults.length} of {zipResults.length} provider{zipResults.length !== 1 ? 's' : ''}{' '}
                {radius > 0 ? `within ${radius} miles of ${zip}` : `in ${zip}`}
              </p>

              {visibleResults.length === 0 ? (
                <p className="providers-empty">No providers match the selected filters.</p>
              ) : (
                <ul className="provider-list">
                  {visibleResults.map((p) => (
                    <li key={p.NPI} className="provider-card">
                      <div className="provider-name">
                        {p['First Name']} {p['Last Name']}
                        {p.Credential && <span className="provider-cred">, {p.Credential}</span>}
                        {/* Gender pill — only shows when the CSV has data for it */}
                        {genderLabel(p.Gender) && (
                          <span className="provider-gender">{genderLabel(p.Gender)}</span>
                        )}
                        {/* Medicare pill — shows when the NPI is in the CMS
                            Doctors & Clinicians dataset (= enrolled in Medicare) */}
                        {medicareNpis[p.NPI] && (
                          <span className="provider-medicare">Medicare</span>
                        )}
                        {/* Distance badge — only meaningful on radius searches */}
                        {radius > 0 && (
                          <span className="provider-distance">
                            {p.distanceMiles < 0.5 ? '< 1 mi' : `${p.distanceMiles.toFixed(1)} mi`}
                          </span>
                        )}
                      </div>
                      {p.Specialty && <div className="provider-specialty">{p.Specialty}</div>}
                      <div className="provider-details">
                        {p.Address && (
                          <span>{p.Address}, {p.City}, {p.State} {p.ZIP}</span>
                        )}
                        {p.Phone && <span>{p.Phone}</span>}
                      </div>
                    </li>
                  ))}
                </ul>
              )}
            </>
          )}
        </div>
      )}
    </section>
  )
}

export default Providers
