name: pylint all python files
on:
  push:

jobs:
  pylint:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - run: python3 --version
      - run: pip install pylint
      - run: pylint *.py